insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (1, 'Esdras Winterton', '2020-06-18', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (2, 'Bentlee Novello', '2022-04-25', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (3, 'Marlo Battabee', '2022-01-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (4, 'Dorene Yurmanovev', '2022-09-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (5, 'Sadie Claydon', '2020-01-05', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (6, 'Angelo Byham', '2022-02-14', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (7, 'Tynan Hause', '2020-06-14', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (8, 'Hillyer Klimas', '2022-06-11', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (9, 'Marlyn Dupoy', '2022-06-09', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (10, 'Sayres Dell ''Orto', '2020-06-13', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (11, 'Trenton Balchin', '2022-03-27', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (12, 'Tish Cottie', '2022-11-08', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (13, 'Zora Vlasyuk', '2022-11-17', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (14, 'Berni Kitchiner', '2022-02-21', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (15, 'Lucita Domke', '2022-05-25', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (16, 'Marcia McFater', '2022-01-17', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (17, 'Jaquelin Veel', '2022-07-25', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (18, 'Thayne Lowes', '2020-11-15', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (19, 'Conn McGilvray', '2021-12-15', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (20, 'Terri Pockett', '2021-12-17', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (21, 'Wylie Late', '2020-09-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (22, 'Shirley Feenan', '2022-11-26', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (23, 'Philippine Schulken', '2020-11-09', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (24, 'Therine Wakley', '2021-08-11', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (25, 'Isidora Gallienne', '2020-05-28', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (26, 'Antone Kornyshev', '2021-09-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (27, 'Lucinda Elderidge', '2021-05-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (28, 'Gay Dimblebee', '2021-01-16', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (29, 'Jasmine Gilfoyle', '2022-02-23', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (30, 'Gallard Smaleman', '2021-05-22', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (31, 'Aube Capehorn', '2021-01-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (32, 'Katy Charlon', '2022-08-22', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (33, 'Galen Goney', '2020-06-30', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (34, 'Esmeralda Delhay', '2021-10-26', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (35, 'Amabelle Keast', '2022-11-27', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (36, 'Minni Broune', '2020-06-29', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (37, 'Liza Dusting', '2022-02-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (38, 'Tamar Stille', '2022-02-17', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (39, 'Rozina Lawrey', '2020-01-13', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (40, 'Millie Newlands', '2020-11-20', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (41, 'Consolata Ryland', '2020-10-11', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (42, 'Fonzie Harrill', '2022-05-08', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (43, 'Estel Wolffers', '2022-04-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (44, 'Farra Tomney', '2022-02-12', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (45, 'Derward Ivanovic', '2022-10-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (46, 'Major Ambrosoni', '2020-04-05', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (47, 'Dale O''Dyvoy', '2021-01-10', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (48, 'Fee Stigger', '2022-07-12', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (49, 'Dun Digle', '2020-11-05', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (50, 'Elmo Wheeliker', '2022-11-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (51, 'Lion Farnan', '2021-11-30', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (52, 'Deanne Dunbobin', '2020-05-04', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (53, 'Claiborn Deverell', '2022-12-22', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (54, 'Lila Stoppe', '2020-11-28', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (55, 'Marcelle Spinas', '2021-03-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (56, 'Bernette McGiff', '2022-09-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (57, 'Rog Juden', '2021-05-16', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (58, 'Burton Attwill', '2021-10-19', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (59, 'Rockwell Le - Count', '2021-11-25', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (60, 'Cordell Drysdall', '2021-04-12', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (61, 'Vin Allon', '2022-11-28', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (62, 'Nicoli Joslow', '2021-05-04', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (63, 'Layne Sollon', '2022-09-03', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (64, 'Lucius Jenkin', '2021-08-09', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (65, 'Romonda Duffit', '2022-09-22', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (66, 'Alwin Stitt', '2022-10-26', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (67, 'Troy Barta', '2020-11-14', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (68, 'Gisella Slide', '2020-02-16', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (69, 'Taddeo Badcock', '2020-12-03', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (70, 'Ferris Champe', '2021-10-12', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (71, 'Carrissa Weedon', '2021-03-15', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (72, 'Caressa Saphin', '2021-10-30', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (73, 'Jermain Blay', '2021-05-31', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (74, 'Arlee Havercroft', '2021-02-07', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (75, 'Ynes Shulem', '2021-04-06', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (76, 'Ami Salliss', '2022-11-15', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (77, 'Virgilio Warburton', '2020-03-23', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (78, 'Bethena Dignan', '2022-09-10', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (79, 'Cash Skokoe', '2021-12-28', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (80, 'Claiborn Sergent', '2020-01-15', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (81, 'Mikol Cisar', '2021-02-24', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (82, 'Angie Ingman', '2020-09-03', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (83, 'Leisha Piotrkowski', '2022-06-07', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (84, 'Ardith Pomery', '2021-04-24', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (85, 'Hilliary Frears', '2021-03-07', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (86, 'Henrieta Santarelli', '2022-04-26', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (87, 'Brittney Harnetty', '2021-01-23', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (88, 'Sauncho Sloat', '2021-01-27', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (89, 'Zia Urpeth', '2021-01-05', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (90, 'Loralee Ashforth', '2021-06-17', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (91, 'Fred Gimber', '2020-04-28', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (92, 'Merci Ancliff', '2022-03-03', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (93, 'Clarissa Lewsey', '2020-10-07', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (94, 'Benedick Lancetter', '2021-12-11', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (95, 'Perren Hylands', '2022-02-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (96, 'Sibby Crisford', '2022-06-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (97, 'Cleopatra Neil', '2021-11-23', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (98, 'Phillipe Gillio', '2022-04-11', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (99, 'Ashlie Challis', '2022-01-08', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (100, 'Evered Gillison', '2020-07-25', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (101, 'Naoma Cove', '2020-08-10', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (102, 'Jonas Crier', '2021-04-11', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (103, 'Johannes Dri', '2022-01-26', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (104, 'Prinz Andreucci', '2021-08-25', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (105, 'Ruddie Evens', '2022-12-18', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (106, 'Jerrold Lillicrap', '2021-05-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (107, 'Flemming Semper', '2020-02-16', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (108, 'Anette Pentelo', '2021-01-09', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (109, 'Quincey St Ledger', '2022-10-03', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (110, 'Margaux Lathe', '2020-11-02', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (111, 'Jessey Baptiste', '2020-03-19', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (112, 'Almeda Heaviside', '2021-07-04', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (113, 'Carissa Peizer', '2022-03-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (114, 'Mae Cutridge', '2020-04-07', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (115, 'De Priddle', '2020-10-06', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (116, 'Wilburt Ferens', '2020-09-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (117, 'Davis Pockey', '2022-10-05', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (118, 'Bibbie Cagan', '2022-12-27', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (119, 'Darelle Suddick', '2022-07-25', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (120, 'Tuck MacNeice', '2022-12-04', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (121, 'Curry Diggles', '2022-11-19', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (122, 'Deb Bigg', '2022-03-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (123, 'Montgomery Norcock', '2022-06-19', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (124, 'Reginald Regardsoe', '2020-08-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (125, 'Kay Trench', '2022-07-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (126, 'Joe Brastead', '2022-08-04', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (127, 'Alexandrina Glozman', '2020-07-20', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (128, 'Gianina Reckless', '2021-03-04', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (129, 'Leonore Haddick', '2022-11-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (130, 'Walther Kindleside', '2020-02-16', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (131, 'Zabrina Hordle', '2022-02-14', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (132, 'Patsy Botten', '2021-11-27', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (133, 'Kamila McLeoid', '2020-10-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (134, 'Aurore Heathorn', '2020-08-10', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (135, 'Cirilo Caveau', '2022-09-04', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (136, 'May Temperley', '2020-09-06', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (137, 'Franny Esslemont', '2020-11-09', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (138, 'Thorpe Tattershaw', '2021-11-07', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (139, 'Faustina Garrish', '2020-04-21', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (140, 'Dayle Laxon', '2020-03-23', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (141, 'Ofelia Makinson', '2020-02-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (142, 'Ezra Fronks', '2022-08-29', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (143, 'Krystle Polycote', '2021-03-27', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (144, 'Dulcia Weeds', '2020-07-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (145, 'Alysa Fonso', '2022-08-16', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (146, 'Lenard Soppit', '2022-07-11', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (147, 'Neddie Kington', '2022-06-03', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (148, 'Curr Callander', '2020-07-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (149, 'Claudianus Cudby', '2022-02-04', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (150, 'Marleen Kosel', '2020-05-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (151, 'Trina Tunnah', '2020-11-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (152, 'Kennie Pellamont', '2021-07-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (153, 'Galvin Room', '2020-04-22', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (154, 'Denny Borton', '2021-05-16', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (155, 'Elizabet Skelbeck', '2022-09-07', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (156, 'Arlyne Alphonso', '2022-05-12', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (157, 'Angelina Michurin', '2022-10-16', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (158, 'Clay Hobble', '2022-11-22', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (159, 'Wilma Neem', '2021-02-21', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (160, 'Julie Dake', '2022-11-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (161, 'Avram Swinerd', '2022-01-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (162, 'Benni Tirte', '2021-05-30', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (163, 'Jerrylee Scattergood', '2021-09-05', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (164, 'Giffer Bruinemann', '2022-12-09', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (165, 'Wandis Salters', '2020-08-14', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (166, 'Dolley Yellop', '2022-01-29', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (167, 'Holly-anne Oris', '2021-04-01', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (168, 'Deck Downe', '2022-04-07', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (169, 'Robinet Levane', '2022-02-12', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (170, 'Carlie Stringfellow', '2020-11-13', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (171, 'Kamilah Membry', '2022-03-30', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (172, 'Kim Tredgold', '2021-06-07', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (173, 'Willi Kempster', '2022-11-21', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (174, 'Kimbra Maskrey', '2022-06-20', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (175, 'Arley Arnatt', '2021-02-01', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (176, 'Rhodie Marchiso', '2020-04-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (177, 'Hilly Bolgar', '2020-01-05', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (178, 'Fran Dalgliesh', '2022-03-08', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (179, 'Donni Willatt', '2021-10-20', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (180, 'Frederica Murgatroyd', '2021-08-19', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (181, 'Delores Kilpatrick', '2021-05-31', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (182, 'Cherise Exter', '2020-11-21', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (183, 'Baxter Oldroyd', '2022-07-24', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (184, 'Mahala Kidston', '2021-10-15', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (185, 'Fredek Decroix', '2022-02-26', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (186, 'Miguela Karslake', '2020-01-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (187, 'Christabella Rouke', '2020-06-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (188, 'Kass Golding', '2022-04-22', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (189, 'Jeanie Tudgay', '2021-08-08', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (190, 'Miltie Larvin', '2021-04-20', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (191, 'Faythe Stairmond', '2022-02-22', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (192, 'Winona Fleote', '2020-05-10', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (193, 'Major Stolberg', '2022-07-19', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (194, 'Mohandas Harder', '2021-06-26', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (195, 'Olenka Barten', '2021-02-07', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (196, 'Dolley Bartol', '2021-06-29', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (197, 'Gaylor Folkes', '2022-10-19', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (198, 'Jobey Smullen', '2020-03-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (199, 'Hillier Leek', '2020-07-29', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (200, 'Mile Heatly', '2020-09-30', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (201, 'Linzy Melliard', '2022-06-03', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (202, 'Ivette McCollum', '2021-09-28', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (203, 'Farica Gymblett', '2022-05-28', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (204, 'Dewey Ruger', '2021-08-15', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (205, 'Shelby Mooney', '2020-11-26', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (206, 'Molli Yorston', '2020-09-30', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (207, 'Cassey Poyle', '2020-01-26', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (208, 'Mart Hulle', '2022-05-28', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (209, 'Dwain Clayworth', '2020-10-22', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (210, 'Sally Adamowicz', '2020-06-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (211, 'Walsh Hedlestone', '2021-07-05', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (212, 'Wilhelm Tapping', '2020-11-09', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (213, 'Bertrand Coping', '2021-04-24', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (214, 'Chrissy Sarle', '2020-01-08', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (215, 'Mil D''Alesco', '2020-09-25', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (216, 'Roddie Beat', '2021-08-21', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (217, 'Angelita Hartfield', '2022-09-21', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (218, 'Osbourne Bernardos', '2021-04-25', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (219, 'Aile MacGorrie', '2020-08-08', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (220, 'Blondell Espley', '2020-02-10', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (221, 'Caril Williscroft', '2022-03-13', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (222, 'Jana Mangam', '2021-06-04', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (223, 'Madison Corran', '2020-11-17', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (224, 'Fancy Wardhaw', '2020-04-28', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (225, 'Lawrence Piens', '2022-06-05', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (226, 'Billy Nelthorp', '2021-08-01', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (227, 'Rafaela Wiles', '2022-10-31', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (228, 'Ebony Romand', '2021-05-14', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (229, 'Lucien Spriggs', '2021-04-18', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (230, 'Cornelius Dufaire', '2020-02-07', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (231, 'Sandra Rogier', '2021-03-01', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (232, 'Chastity Castagne', '2020-08-24', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (233, 'Modestia Banfield', '2022-03-28', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (234, 'Gwynne Boeter', '2022-01-21', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (235, 'Johnnie Aharoni', '2020-05-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (236, 'Klarika Bielefeld', '2020-03-23', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (237, 'Cleopatra Adshead', '2021-05-27', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (238, 'Farlay Iannazzi', '2020-03-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (239, 'Ryann Bent', '2020-08-23', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (240, 'Orv Philippsohn', '2020-03-10', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (241, 'Corinne Geraud', '2022-10-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (242, 'Andi Frowing', '2021-10-20', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (243, 'Lynnell Chancelier', '2021-02-02', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (244, 'Nannie Mayow', '2022-09-11', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (245, 'Alexina Dedney', '2021-10-30', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (246, 'Marilyn Jeste', '2022-04-10', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (247, 'Danie Renvoys', '2020-01-11', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (248, 'Bearnard Dilks', '2020-05-25', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (249, 'Keenan Giroldi', '2022-09-03', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (250, 'Vale Camock', '2020-03-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (251, 'Florencia Boddington', '2022-04-14', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (252, 'Lorna Gilchriest', '2021-05-23', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (253, 'Carmella Bortolozzi', '2022-02-14', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (254, 'Adriano Chesnut', '2020-04-06', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (255, 'Constancy Creak', '2022-03-01', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (256, 'Howie Farnin', '2020-03-29', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (257, 'Chrissie Manueli', '2020-12-13', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (258, 'Selinda Hradsky', '2021-11-11', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (259, 'Merrilee Ferrieroi', '2020-05-17', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (260, 'Sianna Drivers', '2022-02-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (261, 'Hyacinth Semrad', '2021-09-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (262, 'Nikita Pedersen', '2020-06-08', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (263, 'Ronalda Helversen', '2021-08-27', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (264, 'Margette Unworth', '2020-04-29', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (265, 'Lorenza Aynsley', '2020-01-19', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (266, 'Dorian Tilford', '2021-09-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (267, 'Moshe Anstiss', '2021-06-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (268, 'Lalo Padbery', '2022-09-08', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (269, 'Ferne Ghilks', '2020-03-06', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (270, 'Dulciana Zimmermanns', '2021-10-30', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (271, 'Berton Redolfi', '2021-03-25', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (272, 'Misha Tombling', '2020-09-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (273, 'Meier Bedford', '2022-12-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (274, 'Garvin Copo', '2022-04-20', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (275, 'Agathe Divina', '2022-08-03', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (276, 'Elysha Jose', '2020-02-09', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (277, 'Lavinia Emanulsson', '2020-11-14', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (278, 'Selby Fawloe', '2020-04-23', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (279, 'Terry Brands', '2020-12-19', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (280, 'Mommy Santer', '2021-05-29', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (281, 'Emerson O''Neal', '2020-12-09', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (282, 'Etienne Anwell', '2020-09-19', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (283, 'Benita Bortolussi', '2021-02-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (284, 'Sophi Pindar', '2021-11-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (285, 'Enid Adanet', '2022-07-17', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (286, 'Mela Ferrai', '2021-08-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (287, 'Shalne Jenman', '2022-02-09', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (288, 'Boyce Kaesmans', '2020-05-28', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (289, 'Cynde Phelan', '2022-10-13', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (290, 'Alexandre Grunguer', '2021-11-23', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (291, 'Gilda Twiddell', '2021-12-09', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (292, 'Tedra Pratten', '2022-04-23', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (293, 'Trenton Lampitt', '2021-04-07', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (294, 'Meredithe Paget', '2022-05-19', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (295, 'Ram Bramhall', '2020-10-13', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (296, 'Willy Orfeur', '2021-10-26', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (297, 'Sly Kew', '2020-04-26', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (298, 'Coriss Camis', '2022-04-01', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (299, 'Kingston Yarn', '2022-01-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (300, 'Vin Niess', '2020-07-07', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (301, 'Ara Crozier', '2021-03-30', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (302, 'Towney Rieme', '2022-02-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (303, 'Karena Boullen', '2022-03-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (304, 'Windham MacKessock', '2022-10-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (305, 'Brandice Farncombe', '2021-12-31', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (306, 'Melli Merwede', '2021-12-19', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (307, 'Rickard Keatch', '2021-10-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (308, 'Hollie Standon', '2020-02-27', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (309, 'Imojean Bigley', '2021-09-03', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (310, 'Tybalt Banghe', '2021-08-10', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (311, 'Abbie Lindeman', '2022-06-29', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (312, 'Candra Donaghie', '2022-12-13', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (313, 'Sileas Haquard', '2021-12-09', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (314, 'Mickey Laydel', '2020-09-30', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (315, 'Korry Thrower', '2022-03-21', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (316, 'Terry Scantleberry', '2021-03-15', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (317, 'Chaunce Littlechild', '2021-11-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (318, 'Cassius Blaxley', '2022-06-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (319, 'Josselyn Saich', '2020-11-28', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (320, 'Thomasin Slemmonds', '2021-12-29', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (321, 'Townsend D''Ambrosi', '2022-01-15', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (322, 'Shaughn Swire', '2020-07-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (323, 'Frederigo Mindenhall', '2022-09-06', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (324, 'Kandy Prowse', '2021-12-13', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (325, 'Colver Smillie', '2021-03-27', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (326, 'Theodor Jeannon', '2020-09-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (327, 'Aluin O'' Culligan', '2022-04-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (328, 'Bunny Satteford', '2021-06-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (329, 'Kenon Boast', '2021-08-26', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (330, 'Aguie Radclyffe', '2022-03-24', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (331, 'Kacey Barneville', '2021-11-27', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (332, 'Danyette Blakeway', '2021-08-03', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (333, 'Banky Braunston', '2022-01-17', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (334, 'Katusha Trustram', '2022-10-08', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (335, 'Obidiah Lamacraft', '2021-07-09', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (336, 'Rurik Seyffert', '2021-04-09', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (337, 'Modesta Gozzard', '2020-04-12', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (338, 'Hortensia McKee', '2022-08-15', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (339, 'Corenda Anthonies', '2021-11-21', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (340, 'Kelsi Salman', '2020-11-02', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (341, 'Miran Tisun', '2022-03-01', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (342, 'Ulrike Alday', '2022-10-08', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (343, 'Dukie Order', '2020-07-13', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (344, 'Mirna Gamble', '2021-07-30', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (345, 'Essie Slafford', '2021-01-09', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (346, 'Aurora Basil', '2021-09-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (347, 'Dee dee Beames', '2021-09-30', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (348, 'Willabella Fiveash', '2020-05-02', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (349, 'Fredericka Ambrus', '2020-09-22', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (350, 'Gauthier Muggleston', '2020-01-29', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (351, 'Lauren Burchill', '2020-04-04', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (352, 'Daveen Cuttler', '2020-04-01', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (353, 'Wyatt Ingall', '2020-05-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (354, 'Marti O''Scollain', '2020-02-18', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (355, 'Hyacinthie Checcucci', '2021-09-13', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (356, 'Huntley Speak', '2021-10-18', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (357, 'Nita Ondricek', '2021-12-31', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (358, 'Cynthie Dahlen', '2021-12-19', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (359, 'Meggy Tunnow', '2020-08-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (360, 'Linnie MacGrath', '2020-02-19', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (361, 'Wallas Daily', '2020-09-05', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (362, 'Cherry Gronaller', '2021-01-22', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (363, 'Kimmi Hugin', '2022-01-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (364, 'Elora Dilnot', '2021-09-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (365, 'La verne Fliege', '2020-09-11', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (366, 'Diahann Colt', '2020-04-21', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (367, 'Trumann Brandi', '2021-05-13', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (368, 'Bryn Ilyin', '2021-06-29', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (369, 'Mathew Battelle', '2021-05-16', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (370, 'Emelyne Agronski', '2020-07-26', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (371, 'Vi Axford', '2022-03-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (372, 'Munmro Menier', '2021-03-05', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (373, 'Annemarie Minkin', '2020-10-01', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (374, 'Nelly Grain', '2020-02-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (375, 'Cristionna Francklyn', '2021-04-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (376, 'Bonnibelle Bisseker', '2021-01-31', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (377, 'Alexandra Oakenfull', '2022-12-05', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (378, 'Dur Olorenshaw', '2022-02-05', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (379, 'Rennie Fairs', '2020-04-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (380, 'Edan Bride', '2022-11-18', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (381, 'Ahmad Schruyers', '2020-09-22', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (382, 'Adelle Cattermull', '2022-04-09', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (383, 'Lucky Placidi', '2020-08-20', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (384, 'Broddie Lawles', '2021-02-02', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (385, 'Stanleigh Garretson', '2022-07-08', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (386, 'Katine Deguara', '2022-07-04', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (387, 'Temp Antonsson', '2021-05-16', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (388, 'Elsa Kiloh', '2021-02-13', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (389, 'Abbe Kenneford', '2020-06-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (390, 'Schuyler Avo', '2020-08-26', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (391, 'Saul Kelsey', '2021-07-13', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (392, 'Shirlene Rouke', '2022-12-01', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (393, 'Doris Gebbe', '2020-10-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (394, 'Selma Sowley', '2022-01-13', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (395, 'Ardisj Broxap', '2021-10-10', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (396, 'Di Sicily', '2020-03-19', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (397, 'Sissy Pryke', '2020-06-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (398, 'Ronica Stowte', '2022-01-26', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (399, 'Flora Webborn', '2020-04-17', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (400, 'Homerus Stoffer', '2022-06-13', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (401, 'Aluin Tippell', '2020-02-20', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (402, 'Bridget Dumbrill', '2022-09-15', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (403, 'Courtnay Rouf', '2020-04-25', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (404, 'Rustin Kettlestringe', '2022-05-30', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (405, 'Orren Heaphy', '2022-06-03', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (406, 'Percival Kovacs', '2020-05-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (407, 'Darryl Thow', '2022-11-12', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (408, 'Riccardo Pressnell', '2022-06-16', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (409, 'Marianna Spenclay', '2022-02-26', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (410, 'Port Palfreman', '2021-02-15', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (411, 'Bret Wilkenson', '2021-05-11', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (412, 'Norean Borer', '2021-03-27', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (413, 'Lyda Bridger', '2021-01-14', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (414, 'Katerina Sangra', '2021-11-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (415, 'Farlie Reyburn', '2022-10-16', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (416, 'Leslie Lambarth', '2020-12-01', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (417, 'Rodrique Cicchillo', '2022-07-31', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (418, 'Shaylah Martinolli', '2022-01-10', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (419, 'Donny Meachem', '2022-07-07', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (420, 'Caren Bonnaire', '2021-08-01', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (421, 'Ugo Bumphrey', '2021-09-24', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (422, 'Dottie Rooze', '2022-02-01', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (423, 'Ashely Moverley', '2022-09-29', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (424, 'Hugues Argabrite', '2022-05-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (425, 'Lenna Halpen', '2022-04-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (426, 'Alejandro Ordelt', '2020-04-08', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (427, 'Janos Carren', '2021-08-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (428, 'Nichol Woodnutt', '2021-02-06', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (429, 'Tony Gunny', '2021-04-01', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (430, 'Marlin Rathbone', '2020-01-23', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (431, 'Corny Mithon', '2021-12-24', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (432, 'Ilse Kittiman', '2020-05-04', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (433, 'Minor Ivanenko', '2021-07-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (434, 'Burg Foottit', '2021-08-12', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (435, 'Wendye Hepher', '2022-09-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (436, 'Hermon Dennant', '2021-01-04', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (437, 'Roxie Evelyn', '2022-04-09', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (438, 'Shamus Longthorne', '2020-10-26', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (439, 'Janie Gooderham', '2021-07-28', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (440, 'Norrie Olding', '2020-09-10', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (441, 'Theadora Skim', '2022-04-04', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (442, 'Justinn Ewan', '2020-03-04', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (443, 'Cybil Josuweit', '2022-09-28', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (444, 'Bathsheba McAllister', '2022-08-06', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (445, 'Sande Steffan', '2020-02-01', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (446, 'Maggi Kollatsch', '2021-12-26', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (447, 'Maryellen Nizard', '2021-11-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (448, 'Itch Vials', '2022-11-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (449, 'Hubey Olijve', '2021-09-14', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (450, 'Owen Cassely', '2022-03-15', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (451, 'Odilia Branney', '2021-01-20', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (452, 'Dominic Wellesley', '2022-05-15', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (453, 'Nathalia Lapree', '2020-11-06', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (454, 'Chelsie Hasson', '2021-11-24', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (455, 'Ches Lount', '2022-11-26', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (456, 'Dorisa Horlock', '2020-10-13', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (457, 'Bibby Palay', '2020-03-15', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (458, 'Perle Riba', '2020-06-08', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (459, 'Constanta Lindeman', '2022-01-13', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (460, 'Tilda Haye', '2021-04-01', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (461, 'Gayel Stansbie', '2020-06-25', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (462, 'Ches Guerry', '2022-03-14', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (463, 'Beauregard Carroll', '2022-09-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (464, 'Lurlene Yesipov', '2020-02-15', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (465, 'Sonny MacKomb', '2020-03-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (466, 'Quent Fordy', '2022-08-01', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (467, 'Molly Blowne', '2020-11-16', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (468, 'Connor Le Hucquet', '2021-11-10', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (469, 'Licha Chettoe', '2021-01-05', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (470, 'Cara Nind', '2020-03-27', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (471, 'Zelda McGairl', '2020-02-03', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (472, 'Rem Eriksson', '2022-07-10', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (473, 'Aindrea MacGilfoyle', '2022-02-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (474, 'Cullin Bonafant', '2020-09-04', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (475, 'Averill Archdeacon', '2021-12-16', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (476, 'Fay Bohills', '2020-05-18', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (477, 'Alphonse Ricketts', '2021-07-09', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (478, 'Stirling Ferminger', '2021-03-13', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (479, 'Dolley Fidian', '2021-09-08', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (480, 'Ruthy Wrout', '2020-09-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (481, 'Willy Carbine', '2020-12-03', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (482, 'Jodee de Amaya', '2021-06-21', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (483, 'Belle Gilliat', '2022-08-12', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (484, 'Dorian Pluck', '2021-01-29', 'Moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (485, 'Alameda Londors', '2021-02-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (486, 'Clarance Metrick', '2021-08-18', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (487, 'Upton Twitching', '2020-05-06', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (488, 'Krishna Springford', '2021-09-19', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (489, 'Desiri Wheelhouse', '2022-10-29', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (490, 'Etan Murrell', '2021-10-29', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (491, 'Elita Scutchings', '2020-10-31', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (492, 'Kinnie Galloway', '2020-03-14', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (493, 'Kelvin Tetford', '2020-09-13', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (494, 'Pablo Zanutti', '2021-11-30', 'Senior moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (495, 'Reinaldo Ralston', '2021-08-02', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (496, 'Amata Cuxon', '2020-12-26', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (497, 'Breanne Icke', '2020-10-07', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (498, 'Valle Guillot', '2022-08-15', 'Admin');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (499, 'Rubi Waller-Bridge', '2022-05-06', 'Trial moderator');
insert into MODERATORS (Moderator_ID, Mname, Hire_Date, Role) values (500, 'Ansel Mulvagh', '2020-11-03', 'Moderator');
